#! /bin/bash
dir="`pwd`"
for f in `find -maxdepth 1 ! -name "dot_init" -a ! -name "." -a ! \
    -name ".git" -a ! -name ".gitignore" -a ! -name "install" -printf "%f\n"`
do
    rm -r ~/$f
    ln -s $dir/$f ~/$f
done
